namespace Hercules.Diagrams
{
    public enum ArchetypeType
    {
        /*old*/
        Start,
        Success,
        Failure,
        Spawn,
        Objective,
        Dialog,
        Invalid,
        Asset,
        Random,
        Helper,
        Timer,
        /*common*/
        PentaDown,
        PentaLeft,
        PentaRight,
        PentaUp,
        Rhomb,
        Barrel,
        Box,
        Hexagon,
        Trapeze,
        LiteRhomb,
        LiteBarrel,
        LiteBox,
        LiteHexagon,
        LiteTrapeze,
        LitePentaDown,
        LitePentaLeft,
        LitePentaRight,
        LitePentaUp,
        Window,
        /*ai*/
        AiRoot,
        AiSequence,
        AiSelector,
        AiDecorator,
        AiBehaviour,
        AiCondition,
        AiCheck,
        AiParallel,
        AiInterceptor
    }
}