name: Release Hercules

on:
  workflow_dispatch:
    inputs:
      draft:
        description: 'Draft Release'
        required: true
        default: true
        type: boolean

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Hercules.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Publish
      run: dotnet publish Hercules\Hercules.csproj /p:PublishProfile=Hercules\Properties\PublishProfiles\PublishProfile.pubxml

    - name: Inno Setup Action
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
      with:
        path: Setup/Hercules.iss

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: ${{ inputs.draft }}
        files: Setup\Output\hercules_setup.exe
