name: Release Hercules

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Pre-release'
        required: true
        default: true
        type: boolean
      sign:
        description: 'Sign'
        required: true
        default: false
        type: boolean

jobs:

  build:

    runs-on: windows-latest

    env:
      SM_CLIENT_CERT_FILE: D:\\Certificate_pkcs12.p12
      SM_HOST: ${{ secrets.SM_HOST }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Code signing with Software Trust Manager
      if: ${{ inputs.sign }}
      uses: digicert/ssm-code-signing@v1.0.0

    - name: Set up certificate 
      if: ${{ inputs.sign }}
      run: | 
        echo "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > ${{ env.SM_CLIENT_CERT_FILE }}
        smctl credentials save ${{ secrets.SM_API_KEY }} ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
        smctl windows certsync --keypair-alias="${{ secrets.SM_KEYPAIR_ALIAS }}"
      shell: bash

    - name: Publish
      run: dotnet publish Hercules\Hercules.csproj /p:PublishProfile=Hercules\Properties\PublishProfiles\PublishProfile.pubxml /p:BuildNumber=${{ github.run_number }}

    - name: Sign Executables
      if: ${{ inputs.sign }}
      run: |
        smctl sign --fingerprint ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }} --input bin\\hercules.exe --tool signtool
        smctl sign --fingerprint ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }} --input bin\\hercules.dll --tool signtool

    - name: Create rev.conf
      run: echo "${{ github.run_number }}" > rev.conf

    - name: Create installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
      with:
        path: Setup/Hercules.iss

    - name: Sign Installer
      if: ${{ inputs.sign }}
      run: smctl sign --fingerprint ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }} --input Setup\\Output\\hercules_setup.exe --tool signtool

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: ${{ inputs.prerelease }}
        files: |
          Setup/Output/hercules_setup.exe
          rev.conf
